arkhn/pyrog

src/application/components/columnViewer.tsx, src/style.less
Forgot last commit.
Adds "plus button" for adding columns to input columns.
=> Add 'add column' button

package-lock.json, package.json, src/application/actions.tsx, src/application/components/jsonViewer.tsx, src/application/reducers.tsx, src/application/types.tsx, src/application/views/main.tsx, src/style.less
[Issue]( https://github.com/arkhn/fhir-ball-client/issues/1)
Accepts a string JSON and renders as a tree view or a pretty string 
- Add collapse all button
- AA expand all button
- Node clicks callbacks
=> JSON preview component #1

src/application/actions/currentDatabase.tsx, src/application/actions/nameLists.tsx, src/application/components/columnPicker.tsx, src/application/components/selects/stringSelect.tsx, src/application/mockdata/databaseSchema.tsx, src/application/mockdata/mappings.tsx, src/application/mockdata/nameLists.tsx, src/application/reducers/appData.tsx, src/application/reducers/currentDatabase.tsx, src/application/reducers/currentFhirAttribute.tsx, src/application/reducers/currentFhirResource.tsx, src/application/reducers/mapping.tsx, src/application/reducers/nameLists.tsx, src/application/types.tsx, src/application/views/main.tsx
In this PR:
- connection to the only API serving database names and schemas
- small bugfixes for searching and fetching
=> Fetch actuall database name list and database schemas

client/src/application/containers/utils/navbar/index.tsx, client/src/application/containers/utils/navbar/style.less, client/src/application/containers/views/mappingExplorer/index.tsx
Traduction de francais en anglais de "Ajouter une resource" dans le container mapping
=> Ajouter une resource -> Add resource

client/src/components/selects/TSelect.tsx, client/src/components/selects/addResourceSelect.tsx, client/src/components/selects/resourceSelect.tsx, client/src/components/selects/stringSelect.tsx
Fix #35 
Everything is based on a common improvement of TSelect, which can take a `ItemListPredicate<T>` as parameter for global item list modifications
=> Fix #35 about sorting selects widgets

exploration-server/readme.md
Creates new dir for latitudes OSY :tada:
=> Create work space for exploration server

exploration/README.md
Simple folder structure for exploration project
=> Init exploration project with file structure

client/src/components/selects/scriptSelect.tsx, client/src/graphql/queries/cleaningScripts.graphql
Need to change a field name after a modification in the cleaning scripts repo
=> Change code to name

client/src/graphql/queries/attributeInfo.graphql, client/src/views/Mapping/components/InputColumns/index.tsx, server/src/resolvers/Mutation/pyrog.ts
Enable selection of merging scripts
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/arkhn/pyrog/97)
=> Make the merging script great again

server/Dockerfile, server/docker-compose.yml, server/src/constants/index.ts, server/src/resolvers/mapping.ts
=> Handle versionning in mapping export/import

server/.env, server/.gitignore, server/README.md, server/package.json, server/scripts/importMapping.ts, server/src/resolvers/mapping.ts, server/src/rest/upload.ts, server/tsconfig.json, server/yarn.lock
resolves #110 
See README.md for usage.
=> Script import mapping from file

server/Dockerfile, server/package.json, server/scripts/waitForDb.ts
=> Add a script to start the server from docker

client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx, server/src/fhir/definitions.ts
Fix bug in structure definition parsing, notably with backbone element
Fixes #147
=> Fix bug in structure definition parsing

client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx, client/src/components/mapping/FhirMappingPanel/ResourceSelector/Drawer/index.tsx, client/src/components/mapping/FhirMappingPanel/ResourceSelector/index.tsx, client/src/components/sources/index.tsx, client/src/services/selectedNode/actions.tsx, client/src/services/selectedNode/reducer.tsx
Fixes #155
Fixes #153
Should fix a bit of #149
=> Client minor bugfixes

client/src/components/sources/index.tsx, server/src/resolvers/Source.ts
- Enable source deletion when credentials given
- No more roulette russe when deleting sources
=> Fix bugs when deleting source

client/src/components/fhirpipe/index.tsx, client/src/graphql/queries/resources.graphql
- Can only select resources for selected source (fixes #154)
- Fix bug with error messages
- Fix gql queries
- Cannot click several times on run while API call is not over
But still no feedback on ETL progress
=> Improve fhirpipe view

server/src/constants/index.ts, server/src/resolvers/Query.ts, server/src/resolvers/Resource.ts, server/src/resolvers/StructureDefinition.ts, server/src/resolvers/mapping/__snapshots__/v4.test.ts.snap, server/src/resolvers/mapping/index.ts, server/src/resolvers/mapping/v4.test.ts, server/src/resolvers/mapping/v4.ts, server/test/fixtures/chimio-mapping-v3.json, server/test/fixtures/chimio-mapping-v4.json
fhir-pipe needs the definition and source id in the resource mapping
=> Augment mapping export with definition

client/src/components/mapping/ConceptMap/index.tsx, client/src/components/selects/codeSystemSelect.tsx
Prevent Pyrog from crashing when some CodeSystems don't have a title.
Ideally, we'd like a better solution but we need to have Pyrog functional to prepare a demo.
=> Hot fix codesystems

client/src/components/fhirpipe/index.tsx
=> Allow resource filtering in fhirpipe view

client/src/components/mapping/ConceptMap/index.tsx, client/src/components/mapping/index.tsx, client/src/components/mapping/style.scss
- Make tab div scrollable
- Concept map description can stay empty
- Prevent spaces in concept map title
=> Minor interface improvements

client/src/components/authentication/style.scss
=> Signup page is back (fixes #216)

server/src/generated/nexus.ts, server/src/generated/schema.graphql, server/src/permissions/index.ts
Also push some prisma generated file I forgot to push in previous PR
=> Remove permission rule on signup

client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx, client/src/components/sources/collaborators.tsx, client/src/components/sources/index.tsx, client/src/components/sources/sourceCard.tsx, client/src/components/sources/style.scss, client/src/graphql/mutations/createPermission.graphql, client/src/graphql/mutations/deletePermission.graphql, client/src/graphql/queries/sources.graphql, client/src/types.tsx, server/src/generated/nexus.ts, server/src/generated/schema.graphql, server/src/permissions/index.ts, server/src/resolvers/AccessControl.ts, server/src/resolvers/Mutation.ts, server/src/resolvers/Source.ts
=> Add modal to manage collaborators

client/src/components/mapping/TabColumnPicking/DynamicColumnPicker/index.tsx
Goes with PR https://github.com/arkhn/pagai/pull/30
=> Use resourceId in preview route

client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx
we could not expand array of primitives in fhirresourcetree
=> Fix array of primitives in FhirResourceTree (fixes #233)

client/src/components/mapping/Comments/index.tsx, client/src/components/mapping/Comments/style.scss, client/src/components/sources/index.tsx, client/src/components/sources/sourceCard.tsx, client/src/components/sources/style.scss
=> Improve style on comments

server/package.json, server/src/resolvers/mapping/__snapshots__/v1.test.ts.snap, server/src/resolvers/mapping/__snapshots__/v2.test.ts.snap, server/src/resolvers/mapping/__snapshots__/v3.test.ts.snap, server/src/resolvers/mapping/__snapshots__/v4.test.ts.snap, server/src/resolvers/mapping/__snapshots__/v5.test.ts.snap, server/src/resolvers/mapping/__snapshots__/v6.test.ts.snap, server/src/resolvers/mapping/__snapshots__/v7.test.ts.snap, server/src/resolvers/mapping/utils.ts, server/src/resolvers/mapping/v1.test.ts, server/src/resolvers/mapping/v2.test.ts, server/src/resolvers/mapping/v3.test.ts, server/src/resolvers/mapping/v4.test.ts, server/src/resolvers/mapping/v5.test.ts, server/src/resolvers/mapping/v6.test.ts, server/src/resolvers/mapping/v7.test.ts
fiouuu.. hat was hard
Fix #254
=> Consistent IDs when importing a mapping (share IDs across environments)

client/src/components/mapping/FhirMappingPanel/FhirResourceTree/secondaryLabel.tsx, client/src/components/mapping/FhirMappingPanel/FhirResourceTree/style.scss, client/src/components/mapping/TabColumnPicking/StaticValueForm/IdentifierSystemInput/index.tsx, client/src/components/mapping/TabColumnPicking/style.scss
=> Add tooltip on hover secondary label

client/src/components/newSource/index.tsx, server/src/resolvers/Source.ts, server/src/resolvers/mapping/utils.ts
- fix await on createSource
- enable import mapping without comments
- delete comments and columns on cascade when deleting source
=> Some bugfixes

client/src/components/mapping/index.tsx, client/src/components/newSource/index.tsx
The problem was that the `resource` field key was bypassed
=> Fix bug when importing/exporting additional resources

.github/workflows/client.yml
Add Pyrog-client build and publish commands for a new environment
=> build and publish rms image in github workflow

client/src/components/selects/resourceSelect.tsx
=> Enable filtering resources with label

client/scripts/generate_client_env.sh
Adapt github actions to the fact that Pyrog backend url is now pyrog-api
=> adapt scripts to new pyrog backend api url

.github/workflows/client.yml
Not sure it's the cleanest nor if it even works. Maybe it would be better to have a plain script to do that?
=> Clean GH workflow

client/src/components/mapping/InputColumn/index.tsx
=> Improve joins interface

client/src/components/mapping/TableViewer/FhirPreview/index.tsx, client/src/components/mapping/TableViewer/index.tsx
=> Fix bug reclick on same preview

client/src/components/mapping/TableViewer/index.tsx
Table was displayed as loading during preview
=> Fix bug loading table

client/src/components/mapping/ConceptMap/index.tsx
=> Fetch code systems,... only when opening concept map menu

client/.eslintrc, client/package.json, client/src/app.tsx, client/src/components/mapping/index.tsx, client/src/components/sources/index.tsx, client/src/components/sources/sourceCard.tsx, client/src/index.html, client/src/index.js, client/src/index.jsx, client/src/services/selectedNode/reducer.tsx, client/yarn.lock
* Clicking on a source sometimes does not work, the page has to be refreshed -> JSON parse error in Sources component
* Refreshing on a ressource page will lead to a bug (dark page) -> TypeError in Mapping component
=> fix: json parse error on Sources component and TypeError in Mapping component

server/.env, server/package.json, server/src/constants/index.ts, server/src/oauth.ts, server/src/server.ts, server/yarn.lock
Do not merge. Some work needs to be done elsewhere
=> Use token from oauth2 token provider to fetch structure definitions

server/src/constants/index.ts, server/src/permissions/index.ts
Fixes #[issue number] by @[issue author]
=> Skip authorization checks when env=test

client/scripts/generate_client_env.sh
Fixes #[issue number] by @[issue author]
=> Add oauth env vars to script

client/src/components/routes/privateRoute/index.tsx
Fixes #[issue number] by @[issue author]
=> Set user in redux when access tokens in localstorage

server/src/constants/index.ts, server/src/server.ts, server/src/utils.ts
We want to avoid authentication stuff during integration tests.
=> Ignore authentication during tests

server/src/server.ts, server/src/utils.ts
Queries from client to pagai were broken
=> Fix auth header handling in pyrog-server

client/src/components/mapping/index.tsx
=> Fix export additional resources (fix #380)

client/src/components/routes/privateRoute/index.tsx, client/src/oauth/tokenManager.tsx
Same as https://github.com/arkhn/warehouse-api/pull/150
=> Logout on token refresh error

client/src/components/mapping/FhirMappingPanel/FhirResourceTree/index.tsx, client/src/components/mapping/FhirMappingPanel/FhirResourceTree/secondaryLabel.tsx
Fixes #414 by @nriss 
Only display attributes that are filled for readers
=> Only display attributes that are filled for readers

.github/workflows/client.yml, .github/workflows/server.yml, client/.dockerignore, client/.env.docker, client/Dockerfile, client/README.md, client/docker-compose.yml, client/docker-entrypoint.sh, client/package.json, server/.dockerignore, server/.env.docker, server/Dockerfile, server/README.md, server/docker-compose.yml, server/docker-entrypoint.sh
=> [ci] add versioning to CI workflow

server/scripts/migrateLogicalReferencesV8.ts
```
USAGE:\n> yarn run-ts scripts/migrateLogicalReferencesV8.ts <mapping.json> DEST
```
=> Add script to migrate v8 mappings with logicalReferences

server/src/generated/nexus.ts, server/src/generated/schema.graphql, server/src/permissions/index.ts, server/src/resolvers/Mutation.ts, server/src/resolvers/User.ts
=> Add a updateRole mutation

client/src/components/mapping/TableViewer/index.tsx
=> Reset preview data before making a new one

client/src/components/navbar/index.tsx, client/src/components/sources/index.tsx
Fixes #389
Basically dispatching the deselectSource action when needed
=> Deselect source on main page and after logout

client/src/components/mapping/style.scss
=> Fix inputs div max size

client/src/components/mapping/FhirMappingPanel/FhirResourceTree/nodeLabel.tsx, client/src/components/selects/addExtensionSelect.tsx, client/src/components/selects/addSliceSelect.tsx, client/src/components/selects/resourceSelect.tsx
Fixes #435  by @nriss 
* Specify popover interaction on Select component to fix the menu disappearing on click
* Select menu when adding an extension or a slice should appear
=> fix: context menu

server/src/resolvers/mapping/__snapshots__/v9.test.ts.snap, server/src/resolvers/mapping/utils.ts, server/src/resolvers/mapping/v9.test.ts, server/test/fixtures/chimio-mapping-v9.json
Fixes #448 by @nriss 
See issue
=> Add relation when importing condition

client/src/components/mapping/TableViewer/index.tsx, client/src/services/fhir/index.ts
=> Properly handle error in table preview

client/package.json, client/yarn.lock
=> Bump fhir.ts version

client/src/components/mapping/TableViewer/index.tsx
=> Fix table preview

client/src/components/mapping/style.scss
=> Fix component sizes

server/src/resolvers/mapping/utils.ts, server/src/types.ts
Something I had forgotten in the previous work on adding joins to filters and conditions
=> Fix import joins on filters and conditions

client/src/components/mapping/ConceptMap/index.tsx, client/src/types.ts
Fixes (maybe only partially) #484 
Add resourceType field when creating CodeSystem
=> Add resourceType field when creating CodeSystem

client/src/components/mapping/TableViewer/index.tsx, client/src/components/river/index.tsx, client/src/services/batchList/actions.tsx, client/src/services/scripts/actions.tsx
=> Fix URLs for calls to river

client/src/components/mapping/InputCondition/index.tsx, server/prisma/migrations/20210412125610_in_condition_relation/migration.sql, server/prisma/schema.prisma
Quick addition for urgent need
Did I miss something?
=> Add IN relation to conditions

client/src/components/selects/columnSelect.tsx
=> fix(client): join on multiple owners

client/package.json, client/src/components/database/update.tsx, client/src/components/newSource/index.tsx, client/src/components/newSource/style.scss, client/yarn.lock
Fixes https://github.com/arkhn/fhir-river/issues/499
=> feat(client): add switch for service name connection

client/src/components/river/index.tsx, client/src/services/batchList/actions.tsx, client/src/types.ts
Fixes #[issue number] by @[issue author]
=> fix(client): update /api/batches route
